### PR TITLE
Added: Cleaning up industry_ml example.

### PR DESCRIPTION
**Pull request by vishwanath1306**
* Modified industry_ml test framework.
* Changed the readme to account for tearing down volumes.

Partial fix for #279

### CODE REVIEW

**Review by shreyashankar — CHANGES_REQUESTED** [review]
Thanks for this! You'll need to integrate these components you defined into the `industry_ml` pipeline for this to actually run. Something like `@ingest_componont.run(...)` instead of the usual `register` decorator there. Also, you may want to move these component defs to the `industry_ml.py` file to consolidate. LMK if you have any questions :)

**Comment by vishwanath1306** [comment]
I had already done that but looks like I forgot to commit these files. Should the components in `examples/industry_ml_components.py` be moved to `examples/industry_components.py`?

**Comment by shreyashankar** [comment]
Yeah on further thought I think it will be better to put it in the same file until we create a components subdirectory in examples/ (can do in anonher PR). What do you think?

**Comment by vishwanath1306** [comment]
I will put it in a single file; we can figure it out later when we split it into different subdirectories.

**Review by shreyashankar — APPROVED** [review]
LGTM -- thank you!

**Pull request merged**
