### PR TITLE
cli v2.0 init

### LINKED ISSUE #157: CLI command list
Currently we have:

- `recent`
- `history`
- `trace`

We would also like to include:

- `inspect COMPONENT_RUN_ID`
- `ls tags`
- `ls components`
- `ls components --tag=TAG`
- `ls components --owner=NAME`

We can use `get_components_for_owner` and `get_components_for_tag` to make the `ls` commands.

### PR DESCRIPTION
**Pull request by ariG23498**
This is the second iteration of the CLI commands.
The commands list:
- [x] recent
- [x] trace
- [x] history
- [x] inspect
- [ ] ls

@shreyashankar it would be great if I could have a thorough understanding of the `ls` command. I am not sure what we would output with the ls commands.
PS: Closes #157

### CODE REVIEW

**Comment by shreyashankar** [comment]
Good q. On second thought I came up with https://github.com/loglabs/mltrace/issues/157#issuecomment-841715942. What do you think? Open to suggestions :)

**Comment by shreyashankar** [comment]
@ariG23498 how is this going?

**Comment by ariG23498** [comment]
Hey @shreyashankar could not work on the feature lately. I am sorry about that. Will be working on it as soon as I get some time.

**Comment by shreyashankar** [comment]
No worries; sounds good!

**Comment by shreyashankar** [comment]
Bumping this -- otherwise I will take it on! :)

**Comment by ariG23498** [comment]
Sorry @shreyashankar 
I should have been more professional with the PR. Please carry on with this. I would be unavailable to contribute on this.

**Comment by shreyashankar** [comment]
No worries -- thanks for letting me know!

**Comment by shreyashankar** [comment]
Closing to do in a separate PR

**Pull request closed without merging**
